name: flutterhub
description: Github Client built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  fluro: ^1.4.0
  timeago: ^2.0.14

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-R.ttf
          weight: 400
